services:
  redis-db:
    image: redis:latest
    container_name: redis-db
    env_file:
      - .env
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - "redis-data:/data"
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf", "--requirepass", "${REDIS_PASSWORD}"]
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    networks:
      - redis-net

volumes:
  redis-data:

networks:
  redis-net:
    external: true
